# Configuración de video para CREADOR-VIDEOS
# Proyecto: demo
# Creado:   2026-04-18

FILES_FOLDER: assets
TITLE: "TITULO DEMO"
MAIN_AUDIO: "assets/AUDIO/AGENTES_CLASE2_VER3_AUDIORECORTADO_DEMO.mp3"
GUION_COMPLETO: "output/03_guion/guion_consolidado.txt"
FPS: 30
RESOLUTION: "1920x1080"
MAIN_FONT: Inter
BACKGROUND_COLOR: "#fefefe"
MAIN_TEXT_COLOR: "#bd0505"
HIGHLIGHT_TEXT_COLOR: "#e3943b"
COVER_ASSET: "videos/portada.mp4"
COVER_NOTES: "DEMO"

USE_TRANSITIONS: true
TRANSITION_DURATION: 0.5
